#!/usr/bin/env python3
"""Apply Hindi translations to all prototype HTML files.
Equipment names, units, sensor parameters stay in English."""
import os
import re
import sys

# Order matters: longest phrases first to avoid partial matches.
PAIRS = [
    # ===== Long phrases =====
    ("Aeration Blower #2 — Action plan logged", "एयरेशन ब्लोअर #2 — कार्य योजना दर्ज"),
    ("Aeration Blower #2 — Vibration ke ucch level", "एयरेशन ब्लोअर #2 — कंपन ज़्यादा"),
    ("Aeration Blower #2 — High vibration", "एयरेशन ब्लोअर #2 — कंपन ज़्यादा"),
    ("Aeration Blower #2 — Vibration high", "एयरेशन ब्लोअर #2 — कंपन ज़्यादा"),
    ("Aeration Blower #2 — Step", "एयरेशन ब्लोअर #2 — चरण"),
    ("High vibration · Bearing temp 82°", "कंपन ज़्यादा · बेयरिंग तापमान 82°"),
    ("High vibration — diagnosing", "कंपन ज़्यादा — जांच जारी"),
    ("Bearing temp + vibration cross threshold", "बेयरिंग तापमान + कंपन सीमा से ऊपर"),
    ("Multiple parameters out of safe range — supervisor ko inform karein",
     "कई रीडिंग सीमा से बाहर — सुपरवाइज़र को बताएं"),
    ("Sludge wasting badhayein, aeration ko stable rakhein",
     "स्लज वेस्टिंग बढ़ाएं, एयरेशन स्थिर रखें"),
    ("Blower band‑load kam karein, bearing housing temp check karein. Standby blower par switch karein.",
     "ब्लोअर का लोड कम करें, बेयरिंग हाउसिंग का तापमान देखें। स्टैंडबाय ब्लोअर पर स्विच करें।"),
    ("Bulking suspected → wasting overdue → DO low → action: increase RAS, waste sludge, hold DO 2.5.",
     "बल्किंग संभव → वेस्टिंग में देरी → DO कम → कार्य: RAS बढ़ाएं, स्लज वेस्ट करें, DO 2.5 पर रखें।"),
    ("System detected", "सिस्टम ने पाया"),
    ("System insight", "सिस्टम सुझाव"),
    ("SV30 trending high — bulking suspected", "SV30 बढ़ रहा है — बल्किंग संभव"),
    ("Sludge wasting overdue · SRT bahut high", "स्लज वेस्टिंग देर से · SRT बहुत ज़्यादा"),
    ("Aeration tank ka", "एयरेशन टैंक का"),
    ("paani ka rang", "पानी का रंग"),
    ("kaisa dikh raha hai?", "कैसा दिख रहा है?"),
    ("Inlet condition", "इनलेट की स्थिति"),
    ("kaisi hai? Visual check karein.", "कैसी है? देखकर जांचें।"),
    ("DO meter ka", "DO मीटर की"),
    ("manual reading", "मैन्युअल रीडिंग"),
    ("daalein.", "डालें।"),
    ("Naya issue darj karein", "नई समस्या दर्ज करें"),
    ("Saare issues", "सभी समस्याएँ"),
    ("Aaj ka kaam", "आज का काम"),
    ("Issue ka short description likhein...", "समस्या का संक्षिप्त विवरण लिखें..."),
    ("Koi observation likhein...", "कोई जानकारी लिखें..."),
    ("Note likhein...", "नोट लिखें..."),
    ("9:00 AM Reading", "सुबह 9 बजे की रीडिंग"),
    ("Plant Overview", "प्लांट का दृश्य"),
    ("Plant overview", "प्लांट का दृश्य"),
    ("Smart Logbook", "स्मार्ट लॉगबुक"),
    ("Suggested Fix", "सुझाव"),
    ("Suggested fix", "सुझाव"),
    ("Suggested action", "सुझाई गई कार्रवाई"),
    ("Resolution Suggested", "हल का सुझाव"),
    ("Resolution suggested", "हल का सुझाव"),
    ("Escalation Required", "आगे बढ़ाना ज़रूरी"),
    ("Escalation required", "आगे बढ़ाना ज़रूरी"),
    ("Action plan", "कार्य योजना"),
    ("Action plan logged", "कार्य योजना दर्ज"),
    ("Action plan logged · Auto‑monitor 2 hrs", "कार्य योजना दर्ज · 2 घं. ऑटो-मॉनिटर"),
    ("Auto‑monitor 2 hrs", "2 घं. ऑटो-मॉनिटर"),
    ("Issue Resolved", "समस्या हल हुई"),
    ("Plant Supervisor · On-call", "प्लांट सुपरवाइज़र · ऑन-कॉल"),
    ("Tap blower for details", "ब्लोअर पर टैप करें"),
    ("Tap any equipment", "किसी भी मशीन पर टैप करें"),
    ("Tap to open diagnostic flow", "जांच शुरू करने के लिए टैप करें"),
    ("Tap any equipment for details", "मशीन की जानकारी के लिए टैप करें"),
    ("Click any equipment for details", "मशीन की जानकारी के लिए क्लिक करें"),
    ("Detected", "पाया गया"),
    ("Last calibrated:", "पिछला कैलिब्रेशन:"),
    ("Last cleaned 7:30 AM", "आख़िरी सफाई 7:30 AM"),
    ("Last reading", "आख़िरी रीडिंग"),
    ("Last service", "आख़िरी सर्विस"),
    ("Last sludge wasting:", "पिछली स्लज वेस्टिंग:"),
    ("Last wasting", "पिछली वेस्टिंग"),
    ("Last service", "आख़िरी सर्विस"),
    ("Naya Issue · Active", "नई समस्या · सक्रिय"),
    ("Active · Diagnosing", "सक्रिय · जांच जारी"),
    ("In Progress · Diagnosing", "चल रहा है · जांच जारी"),
    ("Resolved · Just now", "हल हुआ · अभी"),
    ("No active alarms", "कोई सक्रिय अलार्म नहीं"),
    ("All systems normal", "सभी सिस्टम सामान्य"),
    ("Just now", "अभी"),
    ("From Shift C · 6:00 AM handover", "शिफ्ट C से · 6:00 AM हैंडओवर"),
    ("Last shift se 2 issues handover hue hain", "पिछली शिफ्ट से 2 समस्याएँ आई हैं"),
    ("Honda Manesar STP", "Honda Manesar STP"),  # plant name as-is
    ("Hello, Ahmed!", "नमस्ते, Ahmed!"),

    # Tab labels (Issues page)
    ("Unresolved · need attention", "हल नहीं हुए · ध्यान दें"),
    ("Open · in progress", "खुले · चल रहे हैं"),
    ("Resolved · today", "हल हुए · आज"),
    ("Resolved · Today", "हल हुए · आज"),

    # Page subtitles
    ("Live · updated 12s ago", "लाइव · 12 सेक. पहले अपडेट"),
    ("Live · updated", "लाइव · अपडेट"),
    ("Shift A · Ranjana A.", "शिफ्ट A · रंजना ए."),
    ("Shift A · 9:00 AM – 5:00 PM", "शिफ्ट A · 9 बजे – 5 बजे"),
    ("Shift A · 9 AM – 5 PM", "शिफ्ट A · 9 बजे – 5 बजे"),
    ("Shift A · 9:00 AM reading window", "शिफ्ट A · 9 बजे रीडिंग का समय"),
    ("Shift A", "शिफ्ट A"),

    # ===== CTA buttons =====
    ("Start Diagnostic", "जांच शुरू करें"),
    ("Open Camera", "कैमरा खोलें"),
    ("or tap to upload", "या अपलोड करें"),
    ("Submit Logbook", "लॉगबुक जमा करें"),
    ("Submit Issue", "समस्या जमा करें"),
    ("Fill Logbook", "लॉगबुक भरें"),
    ("Create Issue", "समस्या दर्ज करें"),
    ("View Issue", "समस्या देखें"),
    ("View all", "सब देखें"),
    ("Show 9 more", "और 9 दिखाएं"),
    ("Show more", "और दिखाएं"),
    ("Escalate Now", "अभी आगे बढ़ाएं"),
    ("Start Now", "अभी शुरू करें"),
    ("Continue → Escalate", "आगे → सुपरवाइज़र"),
    ("+ Add Note", "+ नोट जोड़ें"),
    ("+ नोट जोड़ें", "+ नोट जोड़ें"),  # idempotent
    ("Add Note", "नोट जोड़ें"),
    ("Open mobile prototype", "मोबाइल प्रोटोटाइप खोलें"),
    ("Open desktop view", "डेस्कटॉप व्यू खोलें"),
    ("Open mobile flow", "मोबाइल पर खोलें"),
    ("Open Kanban", "कानबन खोलें"),
    ("Open prototype", "प्रोटोटाइप खोलें"),
    ('Move to Today', 'आज में डालें'),
    ('Move to Upcoming', 'आने वाले में डालें'),
    ('Move to Overdue', 'देर हुए में डालें'),
    ('Move to Done', 'पूरे हुए में डालें'),
    ('Move task', 'काम बदलें'),
    ('Acceptance · High', 'स्वीकार करें · ज़रूरी'),
    ('Accept · High', 'स्वीकार · ज़रूरी'),
    (">Snooze<", ">बाद में<"),
    (">Cancel<", ">रद्द करें<"),
    (">Done<", ">पूरा<"),
    (">Close<", ">बंद<"),
    (">Back<", ">पीछे<"),
    (">Submit<", ">जमा करें<"),
    (">Continue<", ">आगे बढ़ें<"),
    (">Resolve<", ">हल करें<"),
    (">Escalate<", ">आगे बढ़ाएं<"),
    (">Start<", ">शुरू करें<"),
    (">Schedule<", ">शेड्यूल<"),
    (">Accept<", ">स्वीकार<"),
    (">Decline<", ">अस्वीकार<"),
    (">Call<", ">कॉल<"),
    (">Retake<", ">दोबारा लें<"),
    (">Report<", ">रिपोर्ट<"),
    (">+ Report<", ">+ रिपोर्ट<"),
    (">Maintenance<", ">मरम्मत<"),
    (">Pass<", ">सही<"),
    (">Fail<", ">गलत<"),
    (">Filters<", ">फ़िल्टर<"),

    # Tabs - careful: only inside button text
    (">Today <", ">आज <"),
    (">Upcoming <", ">आने वाले <"),
    (">Overdue <", ">देर हुए <"),
    (">Done <", ">पूरे हुए <"),
    (">Unresolved <", ">हल नहीं हुए <"),
    (">Open <", ">खुले <"),
    (">Transferred <", ">पुरानी शिफ्ट <"),
    (">Resolved <", ">हल हुए <"),

    # Standalone status pills/labels - bracketed for safety
    (">Critical<", ">गंभीर<"),
    (">Warning<", ">चेतावनी<"),
    (">In Progress<", ">चल रहा है<"),
    (">In progress<", ">चल रहा है<"),
    (">Resolved<", ">हल हुआ<"),
    (">Pending<", ">बाकी<"),
    (">Completed<", ">पूरा<"),
    (">Healthy<", ">ठीक<"),
    (">Maintenance<", ">मरम्मत<"),
    (">Transferred<", ">पुरानी शिफ्ट<"),
    (">Unresolved<", ">हल नहीं हुआ<"),
    (">Active<", ">सक्रिय<"),
    (">Watch<", ">ध्यान<"),
    (">Out<", ">बाहर<"),
    (">Ok<", ">सही<"),
    (">Due<", ">अभी करें<"),
    (">Live<", ">लाइव<"),
    (">Required<", ">ज़रूरी<"),
    (">Monitor<", ">देखते रहें<"),
    (">Unassigned<", ">किसी को नहीं दिया<"),
    (">Review<", ">देखें<"),
    (">High<", ">ज़्यादा<"),
    (">Medium<", ">मध्यम<"),
    (">Low<", ">कम<"),

    # Verdict labels
    ("Critical · Action needed", "गंभीर · कार्रवाई ज़रूरी"),
    ("Warning · Monitor", "चेतावनी · देखते रहें"),
    ("Healthy · All in range", "ठीक · सब सीमा में"),
    ("Healthy · Stable", "ठीक · स्थिर"),
    ("Healthy · Within limits", "ठीक · सीमा में"),
    ("Healthy · Clean", "ठीक · साफ"),
    ("Healthy · Flow normal", "ठीक · प्रवाह सामान्य"),
    ("Maintenance · Offline", "मरम्मत · बंद है"),
    ("Critical · Just now", "गंभीर · अभी"),
    ("Critical · 2 min ago", "गंभीर · 2 मिनट पहले"),
    ("Critically low", "बहुत कम"),
    ("In ideal range", "सही सीमा में"),
    ("Below ideal", "सीमा से कम"),
    ("Over‑aerated", "ज़्यादा एयरेट"),
    ("Out of range", "सीमा से बाहर"),
    ("In range", "सीमा में"),
    ("Ideal range", "सही सीमा"),

    # Headers / eyebrows
    (">Plant<", ">प्लांट<"),
    (">Issues<", ">समस्याएँ<"),
    (">Tasks<", ">काम<"),
    (">Equipment<", ">मशीनें<"),
    (">Logbook<", ">लॉगबुक<"),
    (">Filters<", ">फ़िल्टर<"),
    (">Severity<", ">गंभीरता<"),
    (">Action plan<", ">कार्य योजना<"),
    (">Notes (optional)<", ">नोट्स (वैकल्पिक)<"),
    (">Notes<", ">नोट्स<"),
    (">Reason<", ">कारण<"),
    (">Summary<", ">सारांश<"),
    (">Specifications<", ">विशेषताएँ<"),
    (">Capacity<", ">क्षमता<"),
    (">Make<", ">मेक<"),
    (">Installed<", ">लगाया गया<"),
    (">Last service<", ">आख़िरी सर्विस<"),
    (">Last reading<", ">आख़िरी रीडिंग<"),
    (">Photo proof<", ">फोटो प्रमाण<"),
    (">Description<", ">विवरण<"),
    (">Equipment type<", ">मशीन प्रकार<"),
    (">Active Issues<", ">सक्रिय समस्याएँ<"),
    (">Recent activity<", ">हाल की गतिविधि<"),
    (">Tasks<", ">काम<"),
    (">Issues<", ">समस्याएँ<"),
    (">Wasting timeline<", ">वेस्टिंग समयरेखा<"),
    (">Task type<", ">काम का प्रकार<"),
    (">Priority<", ">प्राथमिकता<"),

    # Label words (less risky single words via context)
    (">All<", ">सभी<"),
    (">No active issues<", ">कोई सक्रिय समस्या नहीं<"),

    # Hint / utility text
    ("Swipe ke through columns · Tap", "स्वाइप करें · टैप करें"),
    ("to move task", "काम बदलने के लिए"),
    ("Swipe left/right between columns. Tap a card to act, or tap the",
     "कॉलम बदलने के लिए बाएं-दाएं स्वाइप करें। काम करने के लिए कार्ड पर टैप करें, या टैप करें"),
    ("icon to move it.", "आइकन को बदलने के लिए।"),

    # Page-specific micro
    ("Naya Issue · Active", "नई समस्या · सक्रिय"),
    ("Naya Issue", "नई समस्या"),
    ("Latest 7 Day", "पिछले 7 दिन"),
    ("Most widely used", "सबसे ज़्यादा उपयोग"),
    ("System detected", "सिस्टम ने पाया"),

    # Time fragments — keep concise
    (" min ago", " मिनट पहले"),
    (" hr ago", " घंटे पहले"),
    (" hrs ago", " घंटे पहले"),
    (" hrs old", " घंटे पुराना"),
    (" min</span>", " मि.</span>"),
    (" sec ago", " सेकंड पहले"),
    (" days ago", " दिन पहले"),
    (" days old", " दिन पुराना"),
    (" hrs", " घंटे"),
    ("Tomorrow · ", "कल · "),
    ("Yesterday", "बीते कल"),
    ("Today", "आज"),
    ("Was due Yesterday · 4:00 PM", "4:00 PM कल को था"),
    ("Was due Yesterday", "कल को था"),
    ("Was due 5:00 AM", "5:00 AM को था"),
    ("Was due 4:00 PM", "4:00 PM को था"),
    ("Was due", "देर"),

    # Buttons in Hindi labels (safe to translate verbs)
    (">Mobile<", ">मोबाइल<"),
    (">Desktop<", ">डेस्कटॉप<"),
    (">+ Report<", ">+ रिपोर्ट<"),

    # Index page
    ("Open prototype →", "प्रोटोटाइप खोलें →"),
    ("View design system", "डिज़ाइन सिस्टम देखें"),
    ("Design system", "डिज़ाइन सिस्टम"),
    ("Mobile · 390px", "मोबाइल · 390px"),
    ("6 connected screens", "6 स्क्रीन जुड़ी हैं"),
    ("Max 3 layers deep", "ज़्यादा से ज़्यादा 3 परत"),
    ("Hinglish copy", "हिंदी-पहले"),
    ("Built for water treatment plant operators · Hindi/Hinglish · 390px mobile‑first",
     "वॉटर ट्रीटमेंट प्लांट ऑपरेटरों के लिए · हिंदी-पहले · 390px मोबाइल-फ़र्स्ट"),
    ("Start at", "शुरुआत यहाँ से"),
    ("Plant SCADA", "प्लांट SCADA"),
    ("Operator decision system for water treatment plants.",
     "वॉटर ट्रीटमेंट प्लांट के ऑपरेटरों के लिए निर्णय प्रणाली।"),
    ("A real‑time, field‑first prototype. Six connected screens, one design system, Hindi‑first copy. Built for clarity over decoration.",
     "रियल-टाइम, फील्ड-फ़र्स्ट प्रोटोटाइप। छह जुड़ी स्क्रीन, एक डिज़ाइन सिस्टम, हिंदी-पहले लिखाई। सजावट से ज़्यादा स्पष्टता।"),

    # Tile labels
    ("01 · Home", "01 · होम"),
    ("02 · Triage", "02 · छंटाई"),
    ("03 · Plan", "03 · योजना"),
    ("04 · Inspect", "04 · जांच"),
    ("05 · Record", "05 · रिकॉर्ड"),
    ("06 · Raise", "06 · दर्ज"),
    ("07 · System", "07 · सिस्टम"),
    ("Live plant overview with tappable equipment, alarm bar, issue card, transferred banner, logbook.",
     "प्लांट का सीधा दृश्य, मशीनों पर टैप, अलार्म बार, समस्या कार्ड, हैंडओवर बैनर, लॉगबुक।"),
    ("Four tabs: Unresolved, Open, Transferred (shift handover), Resolved.",
     "चार टैब: हल नहीं हुए, खुले, पुरानी शिफ्ट, हल हुए।"),
    ("Kanban — Today / Upcoming / Overdue / Done. Expanded card with checklist + camera.",
     "कानबन — आज / आने वाले / देर हुए / पूरे हुए। चेकलिस्ट + कैमरा वाला विस्तृत कार्ड।"),
    ("Status hero in four states. Active issues, tasks, specs. Maintenance + Report Issue actions.",
     "चार स्थितियों में स्थिति हीरो। सक्रिय समस्याएँ, काम, विशेषताएँ। मरम्मत + रिपोर्ट कार्रवाई।"),
    ("Bulk entry, per‑row range checks, immediate out‑of‑range highlight, inline Add Note / Create Issue.",
     "बल्क एंट्री, हर लाइन के लिए सीमा जांच, तुरंत हाइलाइट, नोट या समस्या दर्ज।"),
    ("Equipment + severity + description + camera (required). Submit goes straight to Issues.",
     "मशीन + गंभीरता + विवरण + कैमरा (ज़रूरी)। जमा करने पर सीधे समस्याओं पर जाता है।"),
    ("Tokens, typography, status, buttons, all card variants, alarm bar states, bottom nav.",
     "टोकन, टाइपोग्राफी, स्थिति, बटन, कार्ड के सभी रूप, अलार्म बार, नीचे का नैव।"),
    ("Entry point", "शुरुआत"),
    ("3 unresolved", "3 हल नहीं हुए"),
    ("3 today", "3 आज"),
    ("8 nodes · 4 states", "8 मशीनें · 4 स्थितियाँ"),
    ("8 parameters · ~3 min", "8 पैरामीटर · ~3 मि."),
    ("Photo required", "फोटो ज़रूरी"),

    # Category words for tasks
    (">Reading<", ">रीडिंग<"),
    (">Cleaning<", ">सफाई<"),
    (">Sample<", ">सैंपल<"),
    (">Logbook<", ">लॉगबुक<"),

    # Action plan items
    ("RAS pump 30 min ke liye", "RAS पंप 30 मिनट के लिए"),
    ("par chalayein", "पर चलाएं"),
    ("Sludge wasting 2 hrs ke andar karein", "स्लज वेस्टिंग 2 घंटे में करें"),
    ("DO ko", "DO को"),
    ("par maintain karein, har 30 min check", "पर रखें, हर 30 मिनट जांचें"),
    ("Next check:", "अगली जांच:"),
    ("ghante baad SV30 dobara measure karein.", "घंटे बाद SV30 दोबारा मापें।"),

    # Misc
    ("Probe ko clean kiya hai?", "प्रोब साफ की है?"),
    ("Calibration valid hai?", "कैलिब्रेशन सही है?"),
    ("DO sensor surface should be free of biofilm",
     "DO सेंसर पर बायोफिल्म नहीं होनी चाहिए"),
    ("Reading visible ho proof ke liye",
     "प्रमाण के लिए रीडिंग साफ दिखे"),
    ("Meter ka photo lein", "मीटर का फोटो लें"),
    ("days ago", "दिन पहले"),
    ("Photo captured", "फोटो लिया गया"),
    ("Captured", "लिया गया"),
    ("Bearing oil due for top‑up", "बेयरिंग ऑयल टॉप-अप ज़रूरी"),
    ("Maintenance team on site · ETA 30 min", "मेन्टेनेंस टीम मौजूद · ETA 30 मि."),
    ("Spare part ordered · awaiting delivery", "स्पेयर ऑर्डर हो गया · आने का इंतज़ार"),
    ("Spare valve store mein hai", "स्पेयर वाल्व स्टोर में है"),
    ("Visual check needed · low priority handover",
     "देखकर जांच ज़रूरी · कम प्राथमिकता वाला हैंडओवर"),
    ("Temporary clamp applied · permanent fix pending",
     "अस्थायी क्लैम्प लगाया · पक्की मरम्मत बाकी"),
    ("Inlet surge above design flow", "इनलेट प्रवाह सीमा से ज़्यादा"),
    ("Design flow", "डिज़ाइन प्रवाह"),
    ("Strange noise", "अजीब आवाज़"),
    ("Leak detected", "रिसाव मिला"),
    ("Odor / smell", "गंध"),
    ("Odor", "गंध"),
    ("Visual abnormal", "देखने में असामान्य"),
    ("Visual", "देखकर"),
    ("Aerator restart", "एयरेटर रीस्टार्ट"),
    ("Manual cleaning done", "हाथ से सफाई हो गई"),
    ("Auto‑recovered", "अपने आप ठीक हुआ"),
    ("Auto-recovered", "अपने आप ठीक हुआ"),

    # Common words for kicker/eyebrow
    ("ETA", "अनुमान"),
    ("filled", "भरे"),
    ("of", "में से"),
    ("out of range", "सीमा से बाहर"),

    # Hindi-first eyebrow per nav
    ("Workspace", "वर्कस्पेस"),
    ("Operator", "ऑपरेटर"),
    ("Tasks today", "आज के काम"),
    ("Resolved", "हल हुए"),

    # Severity option pluralization for clarity (was bare High/Medium/Low handled above)
]

ROOT = os.path.dirname(os.path.abspath(__file__))
TARGETS = ["plant.html", "tasks.html", "issues.html", "report.html",
           "logbook.html", "equipment.html", "desktop.html", "index.html",
           "styleguide.html"]

def main():
    for name in TARGETS:
        path = os.path.join(ROOT, name)
        if not os.path.exists(path):
            print(f"skip {name}: not found")
            continue
        with open(path, "r", encoding="utf-8") as f:
            s = f.read()
        before = s
        for src, dst in PAIRS:
            s = s.replace(src, dst)
        if s != before:
            with open(path, "w", encoding="utf-8") as f:
                f.write(s)
            n = sum(1 for src, _ in PAIRS if src in before)
            print(f"patched {name}")
        else:
            print(f"unchanged {name}")

if __name__ == "__main__":
    main()
